group1 = c(18.2, 20.1, 17.6, 16.8, 18.8, 19.7, 19.1)
group2 = c(17.4, 18.7, 19.1, 16.4, 15.9, 18.4, 17.7)
group3 = c(15.2, 18.8, 17.7, 16.5, 15.9, 17.1, 16.7)
observations = c(group1, group2, group3)
group_numbers = rep(1:3, rep(7, 3))
data_groups = data.frame(observation=observations, group_number=group_numbers)
boxplot(observations~group_numbers, data=data_groups)
aov(observation~group_number, data=data_groups)
summary(aov(observation ~ group_number, data=data_groups))
l<-lm(observation~group_number, data=data_groups)
anova(l)
library(ISwR)
boxplot(folate~ventilation, data=red.cell.folate)
summary(aov(folate~ventilation, data=red.cell.folate))
modified_juul <- juul
modified_juul$tanner <-factor(modified_juul$tanner,
                              labels=c("I","II","III","IV","V"))
summary(aov(igf1~tanner, data=modified_juul))
l<-lm(igf1~tanner, data=modified_juul)
anova(l)
