library(MASS)
data(cats)
str(cats)
slmodel<- lm(Hwt~Bwt, data=cats)
summary(slmodel)
plot(cats$Bwt, cats$Hwt)
plot(cats$Bwt, cats$Hwt, type="n")
abline(lm(Hwt~Bwt, data=cats))
with(cats, points(Bwt[Sex=="F"], Hwt[Sex=="F"], pch=16, col="red"))
with(cats, points(Bwt[Sex=="M"], Hwt[Sex=="M"], pch=19, col="blue"))
temp.df <- predict(slmodel)
abs(predict(slmodel) - cats$Hwt[which(cats$Bwt == 3.7)])
data(mtcars)
str(mtcars)
model1 <- lm(mpg ~ hp, data=mtcars)
model2 <- lm(mpg ~ wt, data=mtcars)
summary(model1)
summary(model2)
library(ISLR)
data(Wage)
summary(lm(wage~age+education+jobclass, data=Wage))
str(Wage)
lm(wage~age+education+jobclass, data=Wage)
